#!/usr/bin/env bash
#
# Copyright (C) 2017 Chunyang Xu
#
# build-emacs - Build Emacs from source

usage () {
    cat <<EOF 1>&2
Usage: ${0##*/} VERSION
Build VERSION of GNU Emacs from source.

Example:
  ${0##*/} 25.2   Build GNU Emacs 25.2 from source.
EOF
}

if [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
    usage
    exit 0
fi

[[ "$1" =~ ^[0-9]*\.[0-9](\.[0-9])?$ ]] || {
    usage
    exit 1
}

VERSION="$1"
EMACS="emacs-$VERSION"
TARBALL="$EMACS.tar.gz"

[[ -f "$TARBALL" ]] || {
    wget --content-disposition "http://ftpmirror.gnu.org/emacs/$TARBALL" || exit 1
}

[[ -d "$EMACS" ]] || {
    tar xzf "$TARBALL" || exit 1
}

cd "$EMACS" || exit 1
if [[ -x src/emacs ]]; then
    src/emacs --version
else
    ./autogen.sh                                              \
        && ./configure --without-x --without-ns --without-all \
        && make                                               \
        && src/emacs --version    
fi
