#!/usr/bin/env ruby
#
# code-prettify - Convert Pandoc's <pre> for Google Code Prettify
#
# Pandoc outputs:
# 
#   <pre class="elisp"><code>...</code></pre>
#
# but Google Code Prettify requires:
#
#   <pre class="prettyprint"><code class="language-el">...</code></pre>
#
# Usage:
#
# $ cat ~/include-code-prettify.html
# <script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js?lang=lisp"></script>
# $ pandoc -s --no-highlight --include-after-body ~/include-code-prettify.html -t html foo.md  | code-prettify
#
# ?lang=lisp is for Emacs Lisp

require "nokogiri"

doc = Nokogiri::HTML(ARGF.read)

doc.css('pre > code').each do |element|
  # Skip if no class in <pre>
  next unless element.parent['class']
  # Skip if the class is Org mode's example block
  next if element.parent['class'] == 'example'

  element['class'] ||= ""
  element.parent['class'].split(/\s+/).each do |cl|
    cl = 'el' if cl == 'elisp'
    element['class'] <<= " language-#{cl}"
  end
  element.parent['class'] = 'prettyprint'
  element['class'] = element['class'].strip
end

print doc.to_html
