#!/usr/bin/env bash
#
# Copyright (C) 2017 Chunyang Xu
#
# git-tree - Treeize the output of git ls-files
#
# Depends: git(1), tree(1), parallel(1)
#
# Known bug: Too slow

usage () {
    echo "Usage: ${0##*/}" 1>&2
    echo "Treeize the output of git ls-files." 1>&2
}

if [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
    usage
    exit 0
fi

if [[ $# -ne 0 ]]; then
    echo "error: too many arguments" 1>&2
    usage
    exit 1
fi

check () {
    not_found=no
    for cmd in "$@"; do
        command -v "$cmd" >/dev/null || {
            echo "$cmd is not installed" 1>&2
            not_found=yes
        }
    done
    [[ $not_found == yes ]] && exit 1
}

check git tree parallel

GIT_DIR="$PWD"

cd "$(mktemp -d)" || exit 1

create () {
    local file="$1"
    if [[ "$file" == */* ]]; then
        [[ -d "${file%/*}" ]] || mkdir -p "${file%/*}"
    fi
    touch "$file"
}
export -f create

set -e
set -o pipefail
git -C "$GIT_DIR" ls-files -z | parallel -0 create

tree
