#!/usr/bin/env ruby
# -*- coding: utf-8; -*-
#
# onejav - 根据番号获得相关信息 via onejav.com
#
# Usage: onejav ID

require 'nokogiri'
require 'open-uri'

def usage
  puts %(\
Usage: #{File.basename __FILE__} ID

ID 由字母和数字构成, 如 'SNIS-928',
字母代表厂商, 数字代表编号,
其中 '-' 可省略, 即 'SNIS928' 亦可.
)
end

if ARGV[0] && ARGV[0] =~ /([a-zA-Z]+)-?([0-9]+)/
  id = "#{$1.downcase}#{$2}"
  url = "https://onejav.com/torrent/#{id}"
  puts "Opening #{url}"
  page = Nokogiri::HTML(open(url))
  actresses = page.css('div.list-actress').map(&:text).map(&:strip)
  description = page.at('meta[name="description"]')['content']
  tags = page.css('span.tag').map(&:text)
  date = page.css('a').select { |x| x['href'] =~ /[0-9]{4}\/[0-9]{2}\/[0-9]{2}/ }.first['href']
  cover = page.css('div.card-group div.card img.img-fluid').first.attr('src')
  puts '女优 => ' + actresses.join(', ')
  puts '简介 => ' + description
  puts '日期 => ' + date
  puts '标签 => ' + tags.join(' ')
  puts "种子 => curl -o #{id}.torrent https://onejav.com/torrent/#{id}/download"
  puts '封面 => ' + cover
  `which imgcat`
  if $?.success?
    system("curl '#{cover}' | imgcat")
  else
    system("curl -O '#{cover}'")
  end
else
  usage
  exit 1
end
