#!/usr/bin/env bash
#
# Copyright (C) 2017 Chunyang Xu
#
# arp-ssh - SSH computer under in the same LAN

# For plain-Bash solution, refer
# https://stackoverflow.com/questions/4922943/test-from-shell-script-if-remote-tcp-port-is-open
if ! command -v nc >/dev/null; then
    echo "$0: nc not found" 1>&2
    exit 1
fi

TIMEOUT_SECONDS=1
SSH_PORT=22

get_hosts () {
    if command -v arp >/dev/null; then
        arp -an | awk -F '[()]' '{ if ($2 ~ /192\.168\.0\..../) print $2 }'
    elif command -v ip >/dev/null; then
        ip neigh | awk '{ if ($1 ~ /192\.168\.0\..../) print $1 }'
    else
        echo "$0: arp or ip not found"  1>&2
        exit 1
    fi
}

# 我的路由器给下面的机器分配的 IP 从 192.168.0.100 起
for HOST in $(get_hosts); do
    if nc -w $TIMEOUT_SECONDS -z $HOST $SSH_PORT &> /dev/null; then
        echo "ssh $HOST $*"
        ssh $HOST "$*"
        break
    fi
done
