#!/usr/bin/env bash
#
# Copyright (C) 2017 Chunyang Xu
#
# arp-ssh - SSH computer under in the same LAN
#
# Usage:
# # 1. Login
# $ ssh-neigh
# # 2. Run a command
# $ ssh-neigh ls -al
# # 3. Print IP
# $ ssh-neigh -q

if ! command -v nmap >/dev/null; then
    echo "$0: nmap not found" 1>&2
    exit 1
fi

localhost () {
    if [[ Linux == "$(uname -s)" ]]; then
        # Strip the tailing space
        hostname --ip-addresses | awk '{ print $1 }'
    else
        ipconfig getifaddr en0
    fi
}

LOCALHOST=$(localhost)

for HOST in $(nmap -oG - -p 22 192.168.0.100/29 | awk '/open/ { print $2 }'); do
    if [[ "$HOST" != "$LOCALHOST" ]]; then
        if [[ "$1" == "-q" ]]; then
            echo $HOST
        else
            echo "sshing $HOST $* ..."
            ssh $HOST "$*"
        fi
        break
    fi
done
