#!/usr/bin/env bash
#
# Copyright (C) 2017 Chunyang Xu
#
# treeize - Treeize the output of git ls-files
#
# Depends: git(1), tree(1)
# Bug: Too slow for 100+ files

if ! [[ -p /dev/stdin ]]; then
    echo "error: not piped input" 1>&2
    echo "usage: git ls-files | ${0##*/}" 1>&2
    exit 1
elif [[ $# -ne 0 ]]; then
    echo "error: too many arguments" 1>&2
    echo "usage: git ls-files | ${0##*/}" 1>&2
    exit 1
fi

command -v tree >/dev/null || {
    echo "tree is not installed" 1>&2
    exit 1
}

cd "$(mktemp -d)" || exit 1

while IFS= read -r file; do
    if [[ "$file" == */* ]]; then
        [[ -d "${file%/*}" ]] || mkdir -p "${file%/*}"
    fi
    touch "$file"
done < /dev/stdin

tree
