#!/usr/bin/env bash
#
# Copyright (C) 2017 Chunyang Xu
#
# unpk - Unpack file archives of various types
#
# See also http://www.nongnu.org/atool/

usage() {
    cat <<EOF 1>&2
Usage: ${0##*/} archive ...
Extract ARCHIVE(s).
EOF
}

if [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
    usage
    exit 0
fi

if test $# -eq 0; then
    echo "Error: too few arguments"
    usage
    exit 1
fi

for f in "$@"; do
    case "$f" in
        *.tar.gz | *.tgz)
            tar xzf "$f"
            ;;
        *.tar.bz2 | *.tbz)
            tar xjf "$f"
            ;;
        *.zip)
            unzip "$f"
            ;;
        *.rar)
            unrar x "$f"
            ;;
        *.tar)
            tar xf "$f"
            ;;
        *.7z)
            7z x "$f"
            ;;
        *)
            echo "file format not supported: $f"
            ;;
    esac
done
